### ISSUE TITLE
Miasta na prawach powiatu mają nieprawidłowy kod TERYT

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/django-teryt-tree#15]
W bazie Fedrowania urzędy reprezentujące miasta na prawach powiatu zdają się mieć nieprawidłowy kod TERYT, tzn. pozbawiony końcówki "011".

Otóż zgodnie z oficjalną bazą danych JST dostępną tutaj: http://administracja.mswia.gov.pl/adm/baza-jst/baza-teleadresowa-jst-d/7788,Baza-teleadresowa-JST-do-pobrania.html urzędy reprezentujące miasta na prawach powiatu (typ_JST: MNP)  powinny mieć kod teryt zakończony sekwencją "011", czyli - patrząc według rodzaju jednostki terytorialnej wg. podziału GUS - właściwy dla reprezentacji gminy miejskiej na tym obszarze.

Tymczasem urzędy reprezentujące miasta na prawach powiatu w bazie Fedrowania mają TERYT czterocyfrowy, co prawdopodobnie jest obciętym z trzech ostatnich zer TERYTEM reprezentuącym powiat.

Ponieważ wszystkie inne sytuacje nadania TERYTU dla jednostek samorządu terytorialnego w bazie Fedrowania wydają się pozostawać zgodne z linkowanym wyżej oficjalnym plikiem ze strony MSWiA a jedynie miasta na prawach powiatu łamią tę konwencję, toteż wygląda to na błąd raczej, niż świadomą decyzję.

**Comment by ad-m** [comment]
Niniejsza biblioteka nie przetwarza żadnych informacji o urzędach, wyłącznie o jednostkach podziału terytorialnego. Błędy w bazie Fedrowania powinny być zgłaszane w repozytorium Fedrowania.
